apiVersion: v2
name: opensearch-cluster
description: A Helm chart for OpenSearch Cluster
type: application

## The opensearch-cluster Helm Chart version
version: 2.9.13

## The operator version
appVersion: 2.9.13
