name: "Publish Release from tag"
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: k8s-operator
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.work'
          cache: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: set Env
        id: github-ver
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}

